### ISSUE TITLE
Request to Add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [Lokeswara-betha/prime_demo#1]
Hello,

I am Maheshwari from the team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start Flutter](https://startflutter.com/), we add open source products that we find helpful to the community & also we provide credits to the author itself.

Let me know if you are interested to showcase your product on our open-source website.

If yes, then I request you to add MIT Licence in your repo.

Also, add screenshots or gifs of your app.

Looking forward to hearing from you

**Comment by Lokeswara-betha** [comment]
yeah sure.

**Comment by maheshwari-1153** [comment]
Can you please add MIT licence

**Comment by Lokeswara-betha** [comment]
Yup. Added
